title: Parcel and Freight Shipping Extension for SAP
# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /blog
description: A powerful embedded shipping platform that uses modern integration technology to tender packages and freight. Activate shipping in your existing SAP system and work directly with your transportation partners.
exclude:
- LICENSE
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: coderay
