title: Jekyll AsciiDoc Quickstart
# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /blog
description: The Jekyll AsciiDoc Quickstart project is a leg-up in starting your own website hosted on GitHub with content based in AsciiDoc.
exclude:
- LICENSE
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: coderay
author:
  name: Hanzou Hattori
  display_name: Hanzou
  gravatar: c66919cb194f96c696c1da0c47354a6a
  email: hanzou@company.com
  web: http://company.com
  twitter: company
  github: hhattori
